### ISSUE TITLE
Support additional features on Viessmann API Binding

### ISSUE THREAD

**Issue by rtuck99** [rtuck99/openhab-binding#1]
![634ce461cd01beac3a12fefe2155cf8286bf2066_2_615x500](https://user-images.githubusercontent.com/4296093/191620200-47a7b0a3-ddbe-4e30-acfe-87eff3b034a5.png)

Support the above items

**Comment by rtuck99** [comment]
[Spreadsheet](https://docs.google.com/spreadsheets/d/1zfuuzFPTXj3yjkTuxQLtJt4fbKjmJ7mX_gN_Ke0WqdU/edit?usp=sharing) containing annotated version of the above.

Summary of current support status in 3.3.0:

Should currently be supported:
- Aussentemperatur
- Kesselsolltemperatur
- Brennerstarts
- Brenner-Betriebsstunden
- Aktuelle Betriebsart A1/M1
- Raumtemperatur Soll Normalbetrieb A1/M1
- Vorlauftemperatur A1/M1
- Heizkreispumpe A1/M1
- Partybetrieb A1/M1
- Frostgefahr Heizkreis A1/M1
- Raumsolltemperatu Partybetrieb A1M1

The following are Advanced Features according to the API documentation and aren't available in the free version of the API. As such they aren't supported and I have no plans to support unless someone already is using the paid-for API and is willing to assist me in supporting it.

- Abgastemperatur
- Forderhohe

The following features I'm either not sure exactly what they correspond to in the API or what their JSON representation is, and will need to get some example JSON response in order to support:

- Interne Pumpe (might be an Advanced Feature, not sure)
- Durchfluss Stromungssensor
- Warmwasserbereitung
- Temperatur Speicher Ladesensor Komfortsensor
- Speicherladepumpe
- Zirkulationspumpe
- Externe Betriebsartenumschaltung A1/M1
- Sparbetrieb A1/M1

The remaining ones, I think I have identified and they are returned by my current setup therefore should not be too difficult to support in a future release.

**Comment by portboy** [comment]
How can I support the process? Do you need access to my API?
I've underlined the important values to decide if the heating system works efficient or not.
Not shown is the return temperature. But this value is very interesting too.
![image](https://user-images.githubusercontent.com/11173760/191766844-673aa217-e696-49ed-901f-9c203b427587.png)

**Comment by rtuck99** [comment]
Should now be fixed in 3.3.2

I've implemented all the features that I could find in the supplied Json file.
You should now have all the features in red apart from:
Interne Pumpe Drezahl - this isn't present in the API
Durchfluss Stromungssensor - ditto
Forderhohe - this is an Advanced Feature and you don't have it

The spreadsheet has been updated with what's now supported
