### ISSUE TITLE
Make commands read/write and add read-only parameters

### ISSUE THREAD

**Issue by agile-it** [rtuck99/openhab-binding#30]
I would like to have the following points writable and not read-only so I can turn off my heating system when leaving the house (for instance):
- `heating.circuits.0.operating.programs.eco`
- `heating.circuits.0.operating.programs.normal`
- `heating.circuits.0.operating.programs.reduced`
- `heating.circuits.0.operating.programs.comfort`

Is it possible to remove the `readOnly="true"` from the `<state>` tag in `thing-types.xml`? 

I would also like to have some data points for energy consumption (mainly gas):
- `heating.gas.consumption.dhw`
- `heating.gas.consumption.heating`
- `heating.gas.consumption.summary.dhw`
- `heating.gas.consumption.summary.heating`
- `heating.gas.consumption.total`

can they just be added as the other values in `thing-types.xml`? Then I can try to make a pull request.

**Comment by rtuck99** [comment]
It seems that in general, only the eco and comfort programs have activate/deactivate commands, and even then only on some systems. The commands aren't always present and when present may be enabled or disabled depending on the state of the system. 

I'm considering what is the best way of surfacing this - as there's not really any way of conveniently indicating  whether the commands are present e.g. by greying out any associated control.

The gas consumption stats should already be visible in the latest release.

**Comment by rtuck99** [comment]
Fixed in 3.4.0
