### ISSUE TITLE
[feature request] Support for ventilation system

### ISSUE THREAD

**Issue by matzebecker** [rtuck99/openhab-binding#37]
The binding supports only heating systems and heat pumps so far. The Vicare API also allows to control ventilation systems that are connected to those heating systems/heat pumps.

Hence, support for ventilation systems, like Vitovent 300-W and 300-F,  are highly appreciated.

**Comment by rtuck99** [comment]
Hi, 
if you have such systems, please visit the OpenHAB binding topic at https://community.openhab.org/t/viessmann-api-binding-for-3-3-x-3-3-0-3-4-0/139087
There you will find information on how to enable the response capture debug setting and you can send me a capture of the API response for your device(s). Then I can add support for it.

**Comment by matzebecker** [comment]
Thank you! Sure, here is the responseCapture: https://drive.google.com/file/d/1yTVB08Nkr-QErxm_H6c-SWWhOTRwEqQz/view?usp=sharing

**Comment by rtuck99** [comment]
Fixed in 3.4.1
