### ISSUE TITLE
[Viessmann API binding] parsing error

### ISSUE THREAD

**Issue by MaTr74** [rtuck99/openhab-binding#65]
Since 2024-10-03 13:20 CEST I get the following error from the binding:

`2024-10-03 13:20:31.903 [WARN ] [ernal.handler.ViessmannBridgeHandler] - Parsing Viessmann response fails: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 15 column 21 path $.data[0].properties.entries.value`

Switching logging to TRACE level gives me a full json response (see attachment).

The binding was working for months without problems.

Environment:
openHAB 4.2.0 and 4.2.2 docker container
Viessmann API binding for OpenHAB 4.0 [4.0.0;5.0.0)
[viessmann.log](https://github.com/user-attachments/files/17283170/viessmann.log)

**Comment by rtuck99** [comment]
These error messages are not from my binding. There is no ViessmannBridgeHandler in my binding.

I believe you should report it here:
https://github.com/smarthomej/addons/issues

**Comment by MaTr74** [comment]
Thanks for clarification!
